# Generated by Django 4.0.4 on 2022-04-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('dateofbirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housingrent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travelexp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foodexp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Utilitybills', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cellphonebill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Groceryexp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Clothingexp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('healthinsurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biodata.student')),
            ],
        ),
    ]
